// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: shortening.proto

package shorteningpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ShorteningServiceClient is the client API for ShorteningService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShorteningServiceClient interface {
	Shorten(ctx context.Context, in *ShortenRequest, opts ...grpc.CallOption) (*ShortenResponse, error)
}

type shorteningServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShorteningServiceClient(cc grpc.ClientConnInterface) ShorteningServiceClient {
	return &shorteningServiceClient{cc}
}

func (c *shorteningServiceClient) Shorten(ctx context.Context, in *ShortenRequest, opts ...grpc.CallOption) (*ShortenResponse, error) {
	out := new(ShortenResponse)
	err := c.cc.Invoke(ctx, "/shortening.ShorteningService/Shorten", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShorteningServiceServer is the server API for ShorteningService service.
// All implementations must embed UnimplementedShorteningServiceServer
// for forward compatibility
type ShorteningServiceServer interface {
	Shorten(context.Context, *ShortenRequest) (*ShortenResponse, error)
	mustEmbedUnimplementedShorteningServiceServer()
}

// UnimplementedShorteningServiceServer must be embedded to have forward compatible implementations.
type UnimplementedShorteningServiceServer struct {
}

func (UnimplementedShorteningServiceServer) Shorten(context.Context, *ShortenRequest) (*ShortenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shorten not implemented")
}
func (UnimplementedShorteningServiceServer) mustEmbedUnimplementedShorteningServiceServer() {}

// UnsafeShorteningServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShorteningServiceServer will
// result in compilation errors.
type UnsafeShorteningServiceServer interface {
	mustEmbedUnimplementedShorteningServiceServer()
}

func RegisterShorteningServiceServer(s grpc.ServiceRegistrar, srv ShorteningServiceServer) {
	s.RegisterService(&ShorteningService_ServiceDesc, srv)
}

func _ShorteningService_Shorten_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShorteningServiceServer).Shorten(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shortening.ShorteningService/Shorten",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShorteningServiceServer).Shorten(ctx, req.(*ShortenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShorteningService_ServiceDesc is the grpc.ServiceDesc for ShorteningService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShorteningService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shortening.ShorteningService",
	HandlerType: (*ShorteningServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Shorten",
			Handler:    _ShorteningService_Shorten_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shortening.proto",
}
