// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: redirection.proto

package redirectionpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RedirectionServiceClient is the client API for RedirectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RedirectionServiceClient interface {
	GetLongURL(ctx context.Context, in *GetOriginalURLRequest, opts ...grpc.CallOption) (*GetLongURLResponse, error)
}

type redirectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRedirectionServiceClient(cc grpc.ClientConnInterface) RedirectionServiceClient {
	return &redirectionServiceClient{cc}
}

func (c *redirectionServiceClient) GetLongURL(ctx context.Context, in *GetOriginalURLRequest, opts ...grpc.CallOption) (*GetLongURLResponse, error) {
	out := new(GetLongURLResponse)
	err := c.cc.Invoke(ctx, "/redirection.RedirectionService/GetLongURL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RedirectionServiceServer is the server API for RedirectionService service.
// All implementations must embed UnimplementedRedirectionServiceServer
// for forward compatibility
type RedirectionServiceServer interface {
	GetLongURL(context.Context, *GetOriginalURLRequest) (*GetLongURLResponse, error)
	mustEmbedUnimplementedRedirectionServiceServer()
}

// UnimplementedRedirectionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRedirectionServiceServer struct {
}

func (UnimplementedRedirectionServiceServer) GetLongURL(context.Context, *GetOriginalURLRequest) (*GetLongURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLongURL not implemented")
}
func (UnimplementedRedirectionServiceServer) mustEmbedUnimplementedRedirectionServiceServer() {}

// UnsafeRedirectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RedirectionServiceServer will
// result in compilation errors.
type UnsafeRedirectionServiceServer interface {
	mustEmbedUnimplementedRedirectionServiceServer()
}

func RegisterRedirectionServiceServer(s grpc.ServiceRegistrar, srv RedirectionServiceServer) {
	s.RegisterService(&RedirectionService_ServiceDesc, srv)
}

func _RedirectionService_GetLongURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOriginalURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedirectionServiceServer).GetLongURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/redirection.RedirectionService/GetLongURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedirectionServiceServer).GetLongURL(ctx, req.(*GetOriginalURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RedirectionService_ServiceDesc is the grpc.ServiceDesc for RedirectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RedirectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "redirection.RedirectionService",
	HandlerType: (*RedirectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLongURL",
			Handler:    _RedirectionService_GetLongURL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "redirection.proto",
}
