// Package handlergen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package handlergen

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error *string `json:"error,omitempty"`
}

// ShortenRequest defines model for ShortenRequest.
type ShortenRequest struct {
	LongUrl *string `json:"long_url,omitempty"`
}

// ShortenResponse defines model for ShortenResponse.
type ShortenResponse struct {
	ShortUrl *string `json:"short_url,omitempty"`
}

// StatsRequest defines model for StatsRequest.
type StatsRequest struct {
	ShortUrl *string `json:"short_url,omitempty"`
}

// StatsResponse defines model for StatsResponse.
type StatsResponse struct {
	LastAccessed *time.Time `json:"last_accessed,omitempty"`
	UsageCount   *int       `json:"usage_count,omitempty"`
}

// PostShortenJSONRequestBody defines body for PostShorten for application/json ContentType.
type PostShortenJSONRequestBody = ShortenRequest

// PostStatsJSONRequestBody defines body for PostStats for application/json ContentType.
type PostStatsJSONRequestBody = StatsRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a short URL
	// (POST /shorten)
	PostShorten(c *gin.Context)
	// Get usage statistics for a short URL
	// (POST /stats)
	PostStats(c *gin.Context)
	// Redirect to the original URL
	// (GET /{short_url})
	GetShortUrl(c *gin.Context, shortUrl string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostShorten operation middleware
func (siw *ServerInterfaceWrapper) PostShorten(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostShorten(c)
}

// PostStats operation middleware
func (siw *ServerInterfaceWrapper) PostStats(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostStats(c)
}

// GetShortUrl operation middleware
func (siw *ServerInterfaceWrapper) GetShortUrl(c *gin.Context) {

	var err error

	// ------------- Path parameter "short_url" -------------
	var shortUrl string

	err = runtime.BindStyledParameterWithOptions("simple", "short_url", c.Param("short_url"), &shortUrl, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter short_url: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetShortUrl(c, shortUrl)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/shorten", wrapper.PostShorten)
	router.POST(options.BaseURL+"/stats", wrapper.PostStats)
	router.GET(options.BaseURL+"/:short_url", wrapper.GetShortUrl)
}
